#!/usr/bin/env python3
"""
Snapshot alloy_enriched.json and append a human-readable changelog of what changed
since the last committed version. Run by refresh.sh after the data steps, before commit.

Builds the historical record that powers future time-series features (churn, ramp curves).

Usage: python3 snapshot.py <YYYY-MM-DD>
"""
import json, sys, subprocess, os

date = sys.argv[1] if len(sys.argv) > 1 else "undated"
cur = json.load(open("alloy_enriched.json"))

# previous = last committed version
prev_raw = subprocess.run(["git", "show", "HEAD:alloy_enriched.json"],
                          capture_output=True, text=True).stdout
try:
    prev = json.loads(prev_raw)
except json.JSONDecodeError:
    prev = []

pj = {l["n"]: l for l in prev}
cj = {l["n"]: l for l in cur}
new = sorted(n for n in cj if n not in pj)
dropped = sorted(n for n in pj if n not in cj)

FIELDS = [("coming_soon", "status"), ("rating", "rating"),
          ("owner", "owner"), ("review_count", "reviews")]
changes = []
for n in sorted(cj):
    if n in pj:
        o, c = pj[n], cj[n]
        for f, label in FIELDS:
            if o.get(f) != c.get(f):
                changes.append(f"{n}: {label} {o.get(f)!r} → {c.get(f)!r}")

# save the snapshot
os.makedirs("snapshots", exist_ok=True)
json.dump(cur, open(f"snapshots/alloy_enriched_{date}.json", "w"), separators=(",", ":"))

# prepend a changelog entry (newest first)
entry = [f"## {date}",
         f"- Total **{len(cur)}** locations ({len(new)} new, {len(dropped)} dropped, {len(changes)} field changes)"]
entry += [f"- 🆕 {n}" for n in new]
entry += [f"- ❌ {n}" for n in dropped]
entry += [f"- ✏️ {c}" for c in changes[:60]]
if len(changes) > 60:
    entry.append(f"- …and {len(changes) - 60} more field changes")
entry.append("")

HDR = "# Data Changelog\n\nAuto-generated by `snapshot.py` on each refresh. Newest first.\n\n"
old = open("CHANGELOG.md").read() if os.path.exists("CHANGELOG.md") else ""
body = old[len(HDR):] if old.startswith(HDR) else old
open("CHANGELOG.md", "w").write(HDR + "\n".join(entry) + "\n" + body)

print(f"snapshot {date}: {len(new)} new, {len(dropped)} dropped, {len(changes)} field changes")
